# List of cops can be found here:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml
# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
  ExtraDetails: true
  TargetRubyVersion: 2.2

# Alot of these metrics are quite restrictive. We may want to disable a few of these.
# For now let's keep them and increase them by an excessive amount

# A calculated magnitude based on number of assignments,
# branches, and conditions.
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500 # default 100

# A complexity metric that is strongly correlated to the number
# of test cases needed to validate a method.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120 # default is 80

# Avoid methods longer than 10 lines of code.
Metrics/MethodLength:
  Max: 20 # default 10

Metrics/ModuleLength:
  Max: 500 # default 100

# A complexity metric geared towards measuring complexity for a human reader.
Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

# Checks if there is a magic comment to enforce string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

# Perfer to use // but %r can be better in certain scenarios
Style/RegexpLiteral:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

# Use %w or %W for arrays of words.
Style/WordArray:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

